import { Service } from "@/types";

export const SERVICES: Service[] = [

  // ─── WOMEN'S HAIR ──────────────────────────────────────────────
  { id: "w-haircut", name: "Hair Cut", category: "Women's Hair", description: "Expert cut tailored to your face shape and style.", duration: 60, price: 800 },
  { id: "w-child-haircut", name: "Child Haircut", category: "Women's Hair", description: "Gentle cut for kids.", duration: 30, price: 400 },
  { id: "w-shampoo-blowdry", name: "Shampoo + Blow Dry", category: "Women's Hair", description: "Wash and smooth blow-dry finish.", duration: 45, price: 500 },
  { id: "w-ironing", name: "Hair Ironing", category: "Women's Hair", description: "Sleek straight finish with professional flat iron.", duration: 60, price: 1200 },
  { id: "w-tongs", name: "Tongs / Curling", category: "Women's Hair", description: "Beautiful curls and waves with tongs.", duration: 60, price: 1200 },
  { id: "w-updo", name: "Up Do's", category: "Women's Hair", description: "Elegant upstyles for events and occasions.", duration: 75, price: 1200 },
  { id: "w-root-touchup", name: "Root Touch Up", category: "Women's Hair", description: "Refresh your colour from root to mid-length.", duration: 90, price: 1300 },
  { id: "w-global-color", name: "Global Hair Colour", category: "Women's Hair", description: "Full head single-process colour.", duration: 120, price: 3400 },
  { id: "w-highlights", name: "Highlights", category: "Women's Hair", description: "Sun-kissed highlights for natural dimension.", duration: 120, price: 4000 },
  { id: "w-inoa-global", name: "Inoa Global Colour", category: "Women's Hair", description: "Ammonia-free L'Oréal Inoa full-head colour.", duration: 120, price: 3700 },
  { id: "w-rebonding", name: "Rebonding / Straightening", category: "Women's Hair", description: "Long-lasting treatment for straight, smooth hair.", duration: 180, price: 6500 },
  { id: "w-hair-spa", name: "Hair Spa", category: "Women's Hair", description: "Deep conditioning spa for soft, nourished hair.", duration: 60, price: 1200 },
  { id: "w-deep-spa", name: "Deep Nourishing Hair Spa", category: "Women's Hair", description: "Absolut Repair intense nourishing treatment.", duration: 75, price: 2000 },
  { id: "w-nanoplastia", name: "Nanoplastia", category: "Women's Hair", description: "Amino acid restoration treatment for smooth, healthy hair.", duration: 180, price: 6500 },
  { id: "w-botox", name: "Hair Botox", category: "Women's Hair", description: "Deep repair filler treatment for thin, damaged hair.", duration: 150, price: 5500 },
  { id: "w-scalp-soothing", name: "Loreal Scalp Soothing Treatment", category: "Women's Hair", description: "Calms sensitive, irritated scalp.", duration: 45, price: 1800 },
  { id: "w-dandruff", name: "Dandruff Treatment", category: "Women's Hair", description: "Brillare targeted dandruff control.", duration: 45, price: 1800 },
  { id: "w-hairfall", name: "Hair Fall Treatment", category: "Women's Hair", description: "Brillare treatment to reduce hair fall.", duration: 45, price: 1800 },
  { id: "w-oil-massage", name: "Oil Head Massage", category: "Women's Hair", description: "Almond or Coconut oil scalp massage.", duration: 30, price: 650 },

  // ─── MEN'S HAIR ────────────────────────────────────────────────
  { id: "m-haircut", name: "Hair Cut", category: "Men's Hair", description: "Classic or modern cut with wash and style.", duration: 30, price: 250 },
  { id: "m-advance-haircut", name: "Men Advance Hair Cut", category: "Men's Hair", description: "Premium advanced styling haircut with expert finish.", duration: 45, price: 300 },
  { id: "m-beard-trim", name: "Beard Trim", category: "Men's Hair", description: "Neat, shaped beard trim.", duration: 20, price: 150 },
  { id: "m-advance-beard", name: "Men Advance Beard", category: "Men's Hair", description: "Premium beard shaping and advanced styling.", duration: 30, price: 300 },
  { id: "m-beard-shave", name: "Beard Shave", category: "Men's Hair", description: "Clean razor shave.", duration: 20, price: 150 },
  { id: "m-beard-styling", name: "Beard Styling", category: "Men's Hair", description: "Creative beard shaping and styling.", duration: 30, price: 200 },
  { id: "m-shampoo-style", name: "Shampoo & Styling", category: "Men's Hair", description: "Wash and style finish.", duration: 25, price: 150 },
  { id: "m-child-haircut", name: "Child Haircut", category: "Men's Hair", description: "Gentle haircut for boys.", duration: 20, price: 200 },
  { id: "m-child-advance-haircut", name: "Child Advance Hair Cut", category: "Men's Hair", description: "Premium advanced styling haircut for kids.", duration: 30, price: 300 },
  { id: "m-beard-colour", name: "Beard Colour", category: "Men's Hair", description: "Natural-looking beard colour.", duration: 30, price: 300 },
  { id: "m-root-touchup", name: "Root Touch Up", category: "Men's Hair", description: "Refresh hair colour at the roots.", duration: 60, price: 800 },
  { id: "m-global-color", name: "Global Hair Colour", category: "Men's Hair", description: "Full head colour treatment.", duration: 75, price: 900 },
  { id: "m-highlights", name: "Highlights", category: "Men's Hair", description: "Partial or full highlights.", duration: 90, price: 1350 },
  { id: "m-rebonding", name: "Rebonding / Straightening", category: "Men's Hair", description: "Long-lasting straight hair treatment.", duration: 150, price: 4000 },
  { id: "m-hair-spa", name: "Hair Spa", category: "Men's Hair", description: "Conditioning spa treatment.", duration: 45, price: 850 },
  { id: "m-nanoplastia", name: "Nanoplastia", category: "Men's Hair", description: "Amino acid hair restoration treatment.", duration: 150, price: 4000 },
  { id: "m-botox", name: "Hair Botox", category: "Men's Hair", description: "Deep repair for thin and damaged hair.", duration: 120, price: 3000 },
  { id: "m-scalp-soothing", name: "Scalp Soothing Treatment", category: "Men's Hair", description: "Loreal scalp calm treatment.", duration: 40, price: 1300 },
  { id: "m-dandruff", name: "Dandruff Treatment", category: "Men's Hair", description: "Targeted dandruff control.", duration: 40, price: 1300 },
  { id: "m-oil-massage", name: "Oil Head Massage", category: "Men's Hair", description: "Almond or Coconut oil scalp massage.", duration: 25, price: 400 },

  // ─── SKINCARE ──────────────────────────────────────────────────
  { id: "sk-threading-brow", name: "Eye Brow Threading", category: "Skincare", description: "Precise eyebrow shaping.", duration: 10, price: 50 },
  { id: "sk-threading-lip", name: "Upper Lip Threading", category: "Skincare", description: "Clean upper lip threading.", duration: 5, price: 30 },
  { id: "sk-threading-full-face", name: "Full Face Threading", category: "Skincare", description: "Complete facial threading.", duration: 25, price: 350 },
  { id: "sk-cleanup-essential", name: "Essential Clean Up", category: "Skincare", description: "Deep cleanse for all skin types.", duration: 45, price: 650 },
  { id: "sk-cleanup-acne", name: "Acne Clean Up", category: "Skincare", description: "Deep clean focused on whiteheads and blackheads.", duration: 45, price: 800 },
  { id: "sk-cleanup-organic", name: "Organic Clean Up", category: "Skincare", description: "Organic deep cleanse for dry or acne-prone skin.", duration: 50, price: 950 },
  { id: "sk-facial-fruit", name: "Fresh Fruit Facial", category: "Skincare", description: "Rejuvenating fresh fruits facial.", duration: 60, price: 1000 },
  { id: "sk-facial-pure-moist", name: "Pure Moist Facial", category: "Skincare", description: "Deep hydration for normal to dry skin.", duration: 60, price: 1350 },
  { id: "sk-facial-whitening", name: "Instant Whitening Facial", category: "Skincare", description: "Brightening facial for even skin tone.", duration: 60, price: 2200 },
  { id: "sk-facial-dead-sea", name: "Dead Sea Mineral Facial", category: "Skincare", description: "Radiant glow with Dead Sea mineral therapy.", duration: 75, price: 2500 },
  { id: "sk-facial-gold", name: "Gold Moroccan Vitamin C Facial", category: "Skincare", description: "Brightening Vitamin C and liquid gold Argan oil facial.", duration: 75, price: 2800 },
  { id: "sk-facial-korean", name: "Korean Glass Skin Facial", category: "Skincare", description: "Intensive hydration for glass-like skin.", duration: 75, price: 4000 },
  { id: "sk-facial-hydra", name: "Hydra Facial", category: "Skincare", description: "Deep pore cleanse with hydra machine.", duration: 75, price: 5000 },
  { id: "sk-facial-gold-karat", name: "24 Karat Ultimo Gold Facial", category: "Skincare", description: "Luxury real gold facial for stunning glowing skin.", duration: 90, price: 5000 },
  { id: "sk-detan-face", name: "De-Tan Face Treatment", category: "Skincare", description: "Essential de-tan for face.", duration: 30, price: 650 },
  { id: "sk-detan-body", name: "De-Tan Full Body", category: "Skincare", description: "Premium full body de-tan treatment.", duration: 90, price: 4000 },
  { id: "sk-bleach-face", name: "Face Bleach", category: "Skincare", description: "Gold or Oxy bleach for face.", duration: 20, price: 500 },
  { id: "sk-bleach-body", name: "Full Body Bleach", category: "Skincare", description: "Full body bleaching treatment.", duration: 90, price: 2500 },
  { id: "sk-body-polish", name: "Body Polishing", category: "Skincare", description: "Essential full body polishing treatment.", duration: 60, price: 4000 },

  // ─── WAXING ────────────────────────────────────────────────────
  { id: "wx-honey-arms", name: "Honey Wax — Full Arms", category: "Waxing", description: "Gentle honey wax, removes tan.", duration: 20, price: 250 },
  { id: "wx-honey-legs", name: "Honey Wax — Full Legs", category: "Waxing", description: "Gentle honey wax for full legs.", duration: 30, price: 350 },
  { id: "wx-honey-body", name: "Honey Wax — Full Body", category: "Waxing", description: "Honey wax full body treatment.", duration: 90, price: 2400 },
  { id: "wx-choc-arms", name: "Chocolate Wax — Full Arms", category: "Waxing", description: "Soothing hydrosoluble chocolate wax.", duration: 20, price: 400 },
  { id: "wx-choc-legs", name: "Chocolate Wax — Full Legs", category: "Waxing", description: "Chocolate wax for full legs.", duration: 30, price: 600 },
  { id: "wx-choc-body", name: "Chocolate Wax — Full Body", category: "Waxing", description: "Chocolate wax full body.", duration: 90, price: 3000 },
  { id: "wx-lipo-arms", name: "Liposoluble Wax — Full Arms", category: "Waxing", description: "Premium wax for sensitive skin.", duration: 20, price: 550 },
  { id: "wx-lipo-legs", name: "Liposoluble Wax — Full Legs", category: "Waxing", description: "Premium wax for full legs.", duration: 30, price: 650 },
  { id: "wx-lipo-body", name: "Liposoluble Wax — Full Body", category: "Waxing", description: "Premium full body waxing.", duration: 90, price: 3500 },
  { id: "wx-bead-face", name: "Bead Wax — Full Face", category: "Waxing", description: "Gentle bead wax for facial hair.", duration: 15, price: 500 },
  { id: "wx-bead-bikini", name: "Bead Wax — Bikini", category: "Waxing", description: "Precision bead wax for bikini area.", duration: 30, price: 2500 },

  // ─── NAILS ─────────────────────────────────────────────────────
  { id: "nl-nail-cut", name: "Nail Cut & File", category: "Nails", description: "Basic nail shaping and file.", duration: 15, price: 150 },
  { id: "nl-organic-mani", name: "Organic Manicure", category: "Nails", description: "Rejuvenating tan removal manicure.", duration: 30, price: 550 },
  { id: "nl-organic-pedi", name: "Organic Pedicure", category: "Nails", description: "Rejuvenating tan removal pedicure.", duration: 40, price: 650 },
  { id: "nl-choc-mani", name: "Chocolate Manicure", category: "Nails", description: "Chocolate mint enriched skin lightening manicure.", duration: 35, price: 650 },
  { id: "nl-choc-pedi", name: "Chocolate Pedicure", category: "Nails", description: "Chocolate mint enriched pedicure.", duration: 45, price: 850 },
  { id: "nl-gel-polish", name: "Gel Polish Application", category: "Nails", description: "Long-lasting chip-free gel polish.", duration: 40, price: 900 },
  { id: "nl-french-gel", name: "French Gel Polish", category: "Nails", description: "Classic French look in gel polish.", duration: 45, price: 900 },
  { id: "nl-gel-ext", name: "Gel Nail Extensions", category: "Nails", description: "Natural gel extensions with gel polish.", duration: 90, price: 3200 },
  { id: "nl-acrylic-ext", name: "Acrylic Nail Extensions", category: "Nails", description: "Natural acrylic extensions with gel polish.", duration: 90, price: 3400 },
  { id: "nl-nail-art", name: "Nail Art", category: "Nails", description: "Creative nail art — glitter, metallic, spider gel and more.", duration: 30, price: 500 },
  { id: "nl-crystal-mani", name: "Crystal SPA Manicure", category: "Nails", description: "Ocean breeze deep hydration manicure.", duration: 50, price: 1200 },
  { id: "nl-crystal-pedi", name: "Crystal SPA Pedicure", category: "Nails", description: "Ocean breeze deep hydration pedicure.", duration: 60, price: 1700 },

  // ─── BRIDAL & GROOM ────────────────────────────────────────────
  { id: "br-bridal-makeup", name: "Bridal Make Up", category: "Bridal & Groom", description: "Complete bridal makeup for your big day.", duration: 120, price: 10000 },
  { id: "br-party-makeup", name: "Light / Party Make Up", category: "Bridal & Groom", description: "Elegant party or event makeup.", duration: 60, price: 5500 },
  { id: "br-trial-makeup", name: "Trial Make Up", category: "Bridal & Groom", description: "Pre-wedding trial makeup session.", duration: 60, price: 2000 },
  { id: "br-pre-bride", name: "Pre-Bride Package", category: "Bridal & Groom", description: "Complete pre-bridal package — facial, wax, polish, manicure, pedicure, clean-up, threading, haircut & spa.", duration: 480, price: 14500 },
  { id: "br-groom", name: "Groom Package", category: "Bridal & Groom", description: "Complete groom package — facial, bleach, tan, haircut, shave, colour, manicure, pedicure & clean-up.", duration: 360, price: 12500 },
];

export const SERVICE_CATEGORIES = [...new Set(SERVICES.map((s) => s.category))];
